### DISCUSSION TITLE
dotnet test --collect:"XPlat Code Coverage" hangs on "Starting test execution, please wait..."

### DISCUSSION THREAD

**Discussion by halimulkazi** [coverlet-coverage/coverlet#1435] [Q&A] [answered]
I am trying to add coverage to the  pipelines, but problem is that it hangs. I tried the donet test which works fine, I don't think the test is the problem as all of the tests hangs.

That's the csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConnectionHandlerManager\ConnectionHandlerManager.csproj" />
  </ItemGroup>

</Project>

```

```
.Unit Test Base: &unitbase
  <<: *jobbase
  script:
    - mkdir coverage-report
    - nuget restore .\XmlServerCore.sln -ConfigFile .\nuget.config
    - dotnet test ...Tests.csproj --collect:"XPlat Code Coverage"
    - mv ../*/coverage.cobertura.xml $CI_PROJECT_DIR/coverage-report/$TEST_PROJECT-coverage.cobertura.xml
  needs: 
    - Build_Debug
  dependencies:
    - Build_Debug
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_JOB_ID"
    paths:
      - $CI_PROJECT_DIR/coverage-report
    expire_in: 3 weeks
```

**Comment by Axeltherabbit** [comment]
same issue for me, and testhost.exe is not killable for some reason, I have to reboot windows

**Comment by ReviveDigitalTeam** [comment]
This issue began for us only after upgrading from net7.0 to net8.0. Our tests run and pass successfully in Visual Studio locally, but not in our ubuntu Azure Pipeline build.
This is using this yaml:
```yaml
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '-c $(buildConfiguration) --collect:"XPlat Code Coverage" --logger trx'
      projects: '**/*Tests/*.csproj'
```
It would get to here and hang indefinitely.
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
```
Removing **--collect:"XPlat Code Coverage"** solved this timeout problem.
