### ISSUE TITLE
Package coverlet.console 3.0.0 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by vladislavzl** [coverlet-coverage/coverlet#1038]
I can't install coverlet.console 3.0.0 for mcr.microsoft.com/dotnet/core/sdk:3.1 image:

`error NU1202: Package coverlet.console 3.0.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package coverlet.console 3.0.0 supports: net5.0 (.NETCoreApp,Version=v5.0) / any`

Is it expected behavior for a new release?

**Comment by MarcoRossignoli** [comment]
Yep we moved .NET Tool to last version. We'll move .NET tool to last version every time we can. 
.NET 5.0 is not a LTS but we'll move to next one on next releases https://github.com/dotnet/core/blob/master/releases.md

**Comment by HughPH** [comment]
OK, but .Net Core 3.1.10 _is_ LTS and expires December 2022
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by MarcoRossignoli** [comment]
Yep I know, the idea was move to 6 next year and release with 5 because is the first "unified version".

Do you have a problem with 5.0, some restrictions?

**Comment by HughPH** [comment]
We have a good number of services that were created targeting .net core 3.1.10, and we wouldn't want to update them all in bulk. This just means, really, that we are restricted to Coverlet 1.7.2 until we make a coordinated effort to migrate to .Net 5.0 - which is not an ideal situation.

The converse question is whether there are certain new Coverlet features that are incompatible with .net core 3.1.10?

**Comment by MarcoRossignoli** [comment]
It's not clear why it's a problem, coverlet console is a .NET tool that instrument and after that run you command+args you don't need to upgrade you project to .NET 5 only install on machine/ci

**Comment by HughPH** [comment]
OK, let me dig into it and get a clear answer for you. It might be that we have a reference to coverlet.console where we actually need the other coverlet packages.

Several people have come up against this now because it's been installed as a package in projects that target netcoreapp31, so it would benefit us all if there's a better answer than "use 1.7.2 or upgrade"

**Comment by MarcoRossignoli** [comment]
> Several people have come up against this now because it's been installed as a package in projects that target netcoreapp31, so it would benefit us all if there's a better answer than "use 1.7.2 or upgrade"

Got it, take a look at guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md

You don't need to reference the tool in your project it runs standalone.

**Comment by HughPH** [comment]
Thanks Marco, that's a big help.

**Comment by MarcoRossignoli** [comment]
I'm going to close for now, feel free to reopen if needed.

**Comment by bjamdort** [comment]
We use dotnet core version 3.1 with ASP but now I can't use the coverlet.console tool. I end up with this error when using coverlet with dotnet 5.0: 
```
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.3 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]
```
Can I still use the tool? It is not possible for us to upgrade to dotnet 5.0

**Comment by MarcoRossignoli** [comment]
> Can I still use the tool? It is not possible for us to upgrade to dotnet 5.0

You don't need to "upgrade" your app, you only need to add net5.0 to pipeline, .NET coverlet tool run with .NET 5.0 runtime, but it's unrelated to your app runtime

**Comment by SabriArslan** [comment]
Hello @MarcoRossignoli 

I'm also having same issue that I can not use coverlet.console v3 anymore within .net core 3.1 SDK docker image.

What I understand is I can not install coverlet.console while using `mcr.microsoft.com/dotnet/core/sdk:3.1` docker image in the pipeline, and in order to install I need to install .net 5 runtime while running inside mcr.microsoft.com/dotnet/core/sdk:3.1`, is this correct ?

If that the case then I need to upgrade all projects that uses coverlet.console otherwise it doesn't make sense install .net 5 runtime while using the 3.1 SDK image.

To give more details, we are using Bitbucket pipelines and my pipeline looks like below
```
build-and-test:
  name: Build and Test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  caches:
    - dotnetcore
  services:
    - docker
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - echo "Building the project"
    - apt-get update 
    - dotnet tool install --global coverlet.console
    - dotnet build
    - dotnet test --no-build --collect:"XPlat Code Coverage" --logger trx -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    .....
```

As you can see installing .net 5 runtime doesn't make sense into container runs with .net core 3.1 SDK.


Could you please consider creating a new coverlet.console V3 package that still supports .net core 3.1 ?

Thanks
