### ISSUE TITLE
lcov file is empty when using C# source generator

### ISSUE THREAD

**Issue by aalmada** [coverlet-coverage/coverlet#1099]
I've been using Coverlet with Coveralls on my project for a long time. I don't know when it started happening but now the report only includes methods from a dependent project.

I'm using the latest versions of `xunit`, `Microsoft.NET.Test.Sdk`, and `coverlet.collector`.  I'm using `net5. 0`. 

In the command line I'm typing: 
`dotnet test ./NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj -f:net5.0 -c:Release --collect:"XPlat Code 
Coverage" --settings coverlet.runsettings --diag:log.txt`

The `coverlet.runsettings` file only has the following:

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>lcov</Format>
          <!-- <Include>[NetFabric.Hyperlinq]*</Include> -->
          <!-- <Exclude>[NetFabric.Assertive]*</Exclude> -->
          <UseSourceLink>true</UseSourceLink>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

In the generated logs I can see references to the classes of my main project but they keep not showing up in the `coverage.info` file.

**Comment by aalmada** [comment]
Here's a portion of the host log:

```TpTrace Verbose: 0 : 14504, 15, 2021/02/23, 23:36:29.866, 1878667252019, testhost.dll, TestExecutionRecorder.RecordResult: Received result for test: NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some.
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.866, 1878667252485, testhost.dll, No DataCollection Data set for the test case 3139059c-ce64-cf4f-db62-ee57dda3ab00
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.866, 1878667252791, testhost.dll, TestRunCache: InProgressTests is null
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.866, 1878667253034, testhost.dll, TestRunCache: No test found corresponding to testResult 'NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some(source: [1], skipCount: -1, takeCount: 9, predicate: Func`3 { Method = Boolean <get_SkipTakePredicateAtSingle>b__113_4(Int32, Int32), Target = <>c { } })' in inProgress list.
TpTrace Verbose: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667253481, testhost.dll, TestExecutionRecorder.RecordResult: Received result for test: NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some.
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667253777, testhost.dll, No DataCollection Data set for the test case 3139059c-ce64-cf4f-db62-ee57dda3ab00
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667254018, testhost.dll, TestRunCache: InProgressTests is null
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667254240, testhost.dll, TestRunCache: No test found corresponding to testResult 'NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some(source: [1], skipCount: 0, takeCount: 9, predicate: Func`3 { Method = Boolean <get_SkipTakePredicateAtSingle>b__113_5(Int32, Int32), Target = <>c { } })' in inProgress list.
TpTrace Verbose: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667254654, testhost.dll, TestExecutionRecorder.RecordResult: Received result for test: NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some.
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667254942, testhost.dll, No DataCollection Data set for the test case 3139059c-ce64-cf4f-db62-ee57dda3ab00
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667255181, testhost.dll, TestRunCache: InProgressTests is null
TpTrace Warning: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667255402, testhost.dll, TestRunCache: No test found corresponding to testResult 'NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some(source: [1], skipCount: 0, takeCount: 9, predicate: Func`3 { Method = Boolean <get_SkipTakePredicateAtSingle>b__113_6(Int32, Int32), Target = <>c { } })' in inProgress list.
TpTrace Verbose: 0 : 14504, 15, 2021/02/23, 23:36:29.867, 1878667255864, testhost.dll, TestExecutionRecorder.RecordResult: Received result for test: NetFabric.Hyperlinq.UnitTests.Element.ElementAt.ReadOnlyListTests.ElementAt_Skip_Take_PredicateAt_With_ValidData_Must_Return_Some.
```

Do all this "no"s mean there's something wrong?

**Comment by petli** [comment]
Am I correct in that unit test only references this project file:
https://github.com/NetFabric/NetFabric.Hyperlinq/blob/Coverage/NetFabric.Hyperlinq/NetFabric.Hyperlinq.csproj

It has these two project references in turn:

```
  <ItemGroup>
    <ProjectReference Include="..\NetFabric.Hyperlinq.Abstractions\NetFabric.Hyperlinq.Abstractions.csproj" />
    <ProjectReference Include="..\NetFabric.Hyperlinq.SourceGenerator\NetFabric.Hyperlinq.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />  
  </ItemGroup>
```

For which of the projects are you getting coverage output?

**Comment by aalmada** [comment]
@petli Hi! 

I'm using GitHub actions to build the solution. Let me point to results that I'm getting.

On the `main` branch, I'm using MSBUILD integration with the following script:

``` YAML
name: Build and test

on: [push]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Test source generator
      run: dotnet test ./NetFabric.Hyperlinq.SourceGenerator.UnitTests/NetFabric.Hyperlinq.SourceGenerator.UnitTests.csproj 
    - name: Build solution
      run: dotnet build
    - name: Tests and coverage
      run: dotnet test ./NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj -f:net5.0 -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=TestResults/ /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByFile="../NetFabric.Hyperlinq.Interfaces/*.cs"
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./NetFabric.Hyperlinq.UnitTests/TestResults/coverage.net5.0.info 
```

You can see in [Coveralls](https://coveralls.io/builds/37404351) that it only includes coverage from classes in `NetFabric.Hyperlinq.Abstractions`. That's a dependency project. 

Please ignore the `ExcludeByAttribute` in the script. It's not doing anything.

After many attempts, I decided to try VS Test integration instead. It can be found in the [`Coverage`](https://github.com/NetFabric/NetFabric.Hyperlinq/tree/Coverage) branch. I changed the script to the following:

``` YAML
name: Build and test

on: [push]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Test source generator
      run: dotnet test ./NetFabric.Hyperlinq.SourceGenerator.UnitTests/NetFabric.Hyperlinq.SourceGenerator.UnitTests.csproj 
    - name: Build solution
      run: dotnet build
    - name: Tests and coverage
      run: dotnet test ./NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj -f:net5.0 -c:Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings
    - name: Get path to lcov file
      id: get_lcov_path
      shell: bash
      run: printf '::set-output name=lcov_path::%s\n' ./NetFabric.Hyperlinq.UnitTests/TestResults/*/coverage.info
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ steps.get_lcov_path.outputs.lcov_path }} 
```

with the  `coverlet.runsettings` as

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>lcov</Format>
          <Include>[NetFabric.Hyperlinq]*</Include>
          <Exclude>[NetFabric.Assertive]*</Exclude>
          <UseSourceLink>true</UseSourceLink>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Now I get the following:

```
Using lcov file: ./NetFabric.Hyperlinq.UnitTests/TestResults/8315cd24-363c-46e7-b38a-f835c342f447/coverage.info
Error:  "2021-02-23T23:21:14.739Z"  'error from lcovParse: ' 'Failed to parse string'
Error:  "2021-02-23T23:21:14.741Z"  'input: ' ''
Error:  "2021-02-23T23:21:14.741Z"  'error from convertLcovToCoveralls'
Error: Failed to parse string
```

This is because the file `coverage.info` is empty.

Sorry for wasting your time but I've tried everything I could...
