### ISSUE TITLE
Coverlet Collector 3.0.3 > Azure DevOps Build Pipeline > No coverage information within coverage report.

### ISSUE THREAD

**Issue by wdspider** [coverlet-coverage/coverlet#1127]
I am struggling to get the coverage report to be populated in an Azure DevOps build pipeline using the .NET CLI task:
```yml
  - task: DotNetCoreCLI@2
    displayName: Restore Packages
    inputs:
      command: restore
      feedsToUse: config
      nugetConfigPath: nuget.config
      restoreArguments: '--locked-mode'
      projects: $(SolutionPath)

  - task: DotNetCoreCLI@2
    displayName: 'Build App - $(BuildConfiguration)'
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(ProjectPath)
      arguments: '--no-restore --configuration $(BuildConfiguration) --output $(BuildResultsPath)'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests - $(BuildConfiguration)'
    inputs:
      command: test
      publishTestResults: false
      projects: $(SolutionPath)
      arguments: '--no-restore --configuration $(BuildConfiguration) --logger trx --results-directory "$(TestResultsPath)" --collect:"XPlat Code Coverage" --settings "$(TestRunSettingsPath)"'
```
Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>

    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>

    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    <PackageReference Include="Moq" Version="4.16.0" />
    <PackageReference Include="Moq.Contrib.HttpClient" Version="1.3.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
test.runsettings file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>opencover,cobertura</Format>
          <UseSourceLink>true</UseSourceLink>
          <IncludeTestAssembly>false</IncludeTestAssembly>
          <SkipAutoProps>true</SkipAutoProps>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector assemblyQualifiedName="Coverlet.Collector.DataCollection.CoverletInProcDataCollector, coverlet.collector, Version=3.0.3.0, Culture=neutral, PublicKeyToken=null"
                     friendlyName="XPlat Code Coverage"
                     enabled="True"
                     codebase="coverlet.collector.dll" />
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
</RunSettings>
```

Unfortunately, the coverage file turns up blank regardless of whether the InProcDataCollectors section is included or not included within the test.runsettings file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession>
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>
```

I have verified that the trx file is correctly populated with passing tests.  In addition, if I run the command locally (i.e. not within the ADO build pipeline); the coverage file is correctly populated as one would expect.  Am I missing something?

**Comment by MarcoRossignoli** [comment]
runsettings doesn't need the inproc element, can you try with:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>opencover,cobertura</Format>
          <UseSourceLink>true</UseSourceLink>
          <IncludeTestAssembly>false</IncludeTestAssembly>
          <SkipAutoProps>true</SkipAutoProps>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

**Comment by wdspider** [comment]
Yes, that's what I originally thought; however, when the coverage file came up empty, I thought that [this known issue](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#upgrade-coverletcollector-to-version--100) might be the problem.  Unfortunately, adding the inproc didn't work as the coverage file still came up empty.  Hence my current confusion as to what is wrong.

**Comment by nikita030493** [comment]
Same issue here. Had to downgrade to 2.9.0

**Comment by wdspider** [comment]
> Same issue here. Had to downgrade to 2.9.0

@nikita030493  I don't see a v2.9.0 in the list:
![image](https://user-images.githubusercontent.com/5971649/111689917-d116e380-87e9-11eb-8642-2e2041759566.png)

**Comment by wdspider** [comment]
I also attempted to use coverlet.msbuild v3.0.3 to no avail either:
![image](https://user-images.githubusercontent.com/5971649/111703121-720d9a80-87fa-11eb-8f5f-425ea90faf2c.png)

**Comment by nikita030493** [comment]
@wdspider I use [coverlet.msbuild](https://www.nuget.org/packages/coverlet.msbuild/) nuget package, not sure what the difference is but it works for me.

**Comment by wdspider** [comment]
Interestingly enough, things started working as expected with the coverlet.collector v3.0.3 package after I rearranged my yml file so that I ran `dotnet test` before `dotnet publish` like so:
```yml
      - task: DotNetCoreCLI@2
        displayName: Restore Packages
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: nuget.config
          restoreArguments: '--locked-mode'
          projects: ${{ parameters.SolutionPath }}

      - task: DotNetCoreCLI@2
        displayName: Run Unit Tests
        inputs:
          command: test
          publishTestResults: false
          projects: ${{ parameters.SolutionPath }}
          arguments: '--no-restore --configuration ${{ parameters.BuildConfig }} --logger trx --results-directory:$(TestResultsPath) --collect:"XPlat Code Coverage" --settings "${{ parameters.TestRunSettingsPath }}"'

      - task: PublishTestResults@2
        displayName: Publish Unit Test Results
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '**/*.trx'
          searchFolder: $(TestResultsPath)

      - task: PublishCodeCoverageResults@1
        displayName: Publish Code Coverage Results
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: $(TestResultsPath)/**/coverage.cobertura.xml

      - task: PublishPipelineArtifact@1
        displayName: 'Publish TestResults Folder'
        inputs:
          targetPath: $(TestResultsPath)
          artifactName: Test Results

      - task: DotNetCoreCLI@2
        displayName: Build Function App
        inputs:
          command: publish
          publishWebProjects: false
          projects: ${{ parameters.FunctionAppProjectPath }}
          arguments: '--no-restore --configuration ${{ parameters.BuildConfig }} --output $(BuildResultsPath)'

      - task: PowerShell@2
        displayName: Rename Build Zip File
        inputs:
          script: Rename-Item -Path Function.zip -NewName '${{ parameters.BuildArtifactName }}.zip'
          targetType: inline
          workingDirectory: $(BuildResultsPath) 

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Build Result'
        inputs:
          targetPath: $(BuildResultsPath)
          artifactName: ${{ parameters.BuildArtifactName }}
```

@MarcoRossignoli - It seems worth adding to the wiki that you need to run `dotnet test` before `dotnet publish` to hopefully save others several hours of troubleshooting.
