### ISSUE TITLE
Azure Dev Ops, Exclude from runsettings

### ISSUE THREAD

**Issue by ranouf** [coverlet-coverage/coverlet#1319]
Hi,

I'm trying to exclude some classes from the code coverage result in the dotnet test command in Azure Dev Ops but the exclude seems to not work.

csproj:

```
<PackageReference Include="coverlet.collector" Version="3.1.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
```

steps:
```
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true --settings tests.runsettings'
    testRunTitle: 'MyProject-Backend-Tests'
```

test.runsettings:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector friendlyName="XPlat code coverage">
				<Configuration>
					<Exclude>[*]*</Exclude>
				</Configuration>
			</DataCollector>
		</DataCollectors>	
	</DataCollectionRunSettings>
</RunSettings>
```

As you can see: [\*]\* is supposed to exclude every thing (source: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#filters)

But As you can see in the report, every thing is still there:
![image](https://user-images.githubusercontent.com/1764519/162284371-30e9a469-0022-4954-8f4d-62cb8f9dcd57.png)

I'm mainly interested to exlude: 
![image](https://user-images.githubusercontent.com/1764519/162284620-fe045f6a-4f88-47ca-a4a0-d7443214583c.png)
and:
I'm not interested to test the migration as it's automatically generated by Entity Framework.

What do I need to modify to exclude the [*.Domains.Infrastructure.Migrations].* and [*.Domains.Infrastructure.SqlServer].*?

Thanks
