### ISSUE TITLE
Coverlet, Multiple TargetFramework, SourceLink, Deterministic Build and Pain

### ISSUE THREAD

**Issue by TommasoBelluzzo** [coverlet-coverage/coverlet#1369]
Hi all. I'm ready to publish a new release of my [FastHashes](https://github.com/TommasoBelluzzo/FastHashes/) library.

I'm running the following configurations for my solution:
- .NET Core 3.1 for my test project, requiring .NET Standard 2.1 library.
- .NET Core 2.1 for my test project, requiring .NET Standard 2.0 library.
- Deterministic build as per **DeterministicBuild.targets**.

**FastHashes.csproj:**
```
<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>`
```

**FastHashes.Tests.csproj:**
```
<ItemGroup>
    <ProjectReference Include="..\FastHashes\FastHashes.csproj" Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
      <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\FastHashes\FastHashes.csproj" Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
      <SetTargetFramework>TargetFramework=netstandard2.1</SetTargetFramework>
    </ProjectReference>
</ItemGroup>
```

I'm running the following GitHub Actions for tests and coverage collection:
```
name: "Continuous Integration"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
    - name: Restore
      working-directory: Solution/
      run: dotnet restore --force-evaluate
    - name: Build
      working-directory: Solution/
      run: dotnet build FastHashes.sln --verbosity normal --configuration Release --no-restore --no-incremental
    - name: Test
      working-directory: Solution/
      run: dotnet test FastHashes.sln --verbosity normal --configuration Release --no-restore --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="lcov" /p:CoverletOutput="../Coverage/" /p:MergeWith="../Coverage/coverage.info"
    - name: Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: Solution/Coverage/coverage.info
```

On my local machine, when I execute the test project, tests are executed and coverage reports are properly produced. This is probably due to the fact that Deterministic Build and SourceLink are disabled. The only problem is that they are not merged into a single file as per **MergeWith** directive:
[local_console.txt](https://github.com/coverlet-coverage/coverlet/files/9364864/local_console.txt)

On the GitHub Actions machine, tests are executed but coverage reports are empty. Of course, no merge file is produced. I would be pleased to attach the log file but "something went really wrong, and we can't process that file".  So let's just insert a workflow run reference: https://github.com/TommasoBelluzzo/FastHashes/actions/runs/2876788194
 
```
2022-08-17T16:17:25.7698646Z ./Solution/Coverage:
2022-08-17T16:17:25.7698891Z total 0
2022-08-17T16:17:25.7699367Z -rw-r--r-- 1 runneradmin 197121 0 Aug 17 16:17 coverage.netcoreapp3.1.info
2022-08-17T16:17:25.7699986Z -rw-r--r-- 1 runneradmin 197121 0 Aug 17 16:16 coverage.netcoreapp2.1.info
```

I think this has something to do with previous issues I already checked. I tried to follow the guidelines for properly setting up the project but I really can't find a way to make my CI work.
