### ISSUE TITLE
Exclude not working on blazor project

### ISSUE THREAD

**Issue by dazinator** [coverlet-coverage/coverlet#1379]
My xunit tests projejct references by backend asp.net core project, which hosts a front end blazor (wasm) project (and hence has a reference to it)

I am attempting to exclude this blazor project from code coverage.

The test is run via an azure devops yaml:

```
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*.Tests*.csproj'
        publishTestResults: true
        arguments: '--configuration $(BuildConfiguration) --no-build --collect "XPlat Code Coverage" /p:CoverletOutputFormat="cobertura%2copencover" /p:SkipAutoProps=true /p:Exclude="[Foo.Client]*"'

```

However after this runs, and I look at the report uploaded to devops, it still shows me types in the Foo.Client assemlby:

![image](https://user-images.githubusercontent.com/3176632/189669387-0e218943-31bb-44b6-9594-07363df48d02.png)

The exclude pattern appears correct to me, am I doing something wrong?
