### ISSUE TITLE
Coverlet does not generate code coverage when having a dependency to Microsoft.SourceLink.GitHub

### ISSUE THREAD

**Issue by gimlichael** [coverlet-coverage/coverlet#940]
### Main Error
After running tests coverlet generates empty cobertura xml file on my build agent

### Agent
Azure Devops - Hosted Agent

### Issue Description

After a long time of diagnostics in regards to this problem, it turns out, that code coverage does not work when having a dependency to Microsoft.SourceLink.GitHub currently in 1.0.0.

**Yaml build step (that works when leaving out SourceLink) **
https://github.com/gimlichael/Cuemon/blob/development/azure-pipelines.yml

```
  - task: DotNetCoreCLI@2
    displayName: 'Test Solution'
    inputs:
      command: 'test'
      projects: test/**/*.csproj
      arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      publishTestResults: true

  - script: reportgenerator "-reports:**/*.opencover.xml" "-targetdir:$(Build.SourcesDirectory)/Coverage" "-reporttypes:Cobertura;HTMLInline;HTMLChart"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Create Code Coverage Reports'
```

**Log output:**

```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Results File: /home/vsts/work/_temp/_fv-az188_2020-08-30_14_43_47.trx

Test Run Successful.
Total tests: 166
     Passed: 166
 Total time: 4.4737 Seconds

Calculating coverage result...
  Generating report '/home/vsts/work/1/s/test/***.Core.Tests/coverage.opencover.xml'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+

```

As I am about to release a major version of my Cuemon project (https://github.com/gimlichael/Cuemon), I would really like to have everything in place - including SourceLink from Microsoft to make my Nuget packages even more reliable.

A workaround, which i am not a fan of, is to remove SourceLink integration.

In case this is prioritized, I have setup a smaller and leaner build pipeline on Azure DevOps (due to extensive build time when integrating with Sonar Cloud).

Failing (with SourceLink): https://dev.azure.com/gimlichael/Cuemon/_build/results?buildId=206&view=results

```
  <ItemGroup Condition="'$(IsTestProject)' == 'false'">
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.2.31" PrivateAssets="all" />
  </ItemGroup>
```

Working (**without** SourceLink): https://dev.azure.com/gimlichael/Cuemon/_build/results?buildId=208&view=results

```
  <ItemGroup Condition="'$(IsTestProject)' == 'false'">
    <!--PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference-->
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.2.31" PrivateAssets="all" />
  </ItemGroup>
```

Thanks in advance for any help that can resolve this issue.

**Note: i have tested with the nightly build, 2.9.1-preview.24.g6479f627e4, unfortunately it DOES NOT resolve the issue (as i figured it might be related to https://github.com/coverlet-coverage/coverlet/issues/882).**

PS
Inspiration for the format of this issue was taken from this issue: https://github.com/coverlet-coverage/coverlet/issues/523 (that seems related - but is not).
